package jysk.ControllerPackage;


/**
* jysk/ControllerPackage/artSequenceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from jysk.idl
* czwartek, 12 grudzieñ 2013 10:31:55 CET
*/

public final class artSequenceHolder implements org.omg.CORBA.portable.Streamable
{
  public jysk.Article value[] = null;

  public artSequenceHolder ()
  {
  }

  public artSequenceHolder (jysk.Article[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = jysk.ControllerPackage.artSequenceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    jysk.ControllerPackage.artSequenceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return jysk.ControllerPackage.artSequenceHelper.type ();
  }

}
