package jysk.ControllerPackage;


/**
* jysk/ControllerPackage/palSequenceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from jysk.idl
* czwartek, 12 grudzieñ 2013 10:31:55 CET
*/

public final class palSequenceHolder implements org.omg.CORBA.portable.Streamable
{
  public jysk.Pallet value[] = null;

  public palSequenceHolder ()
  {
  }

  public palSequenceHolder (jysk.Pallet[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = jysk.ControllerPackage.palSequenceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    jysk.ControllerPackage.palSequenceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return jysk.ControllerPackage.palSequenceHelper.type ();
  }

}
