package jysk.ControllerPackage;


/**
* jysk/ControllerPackage/palSequenceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from jysk.idl
* czwartek, 12 grudzieñ 2013 10:31:55 CET
*/

abstract public class palSequenceHelper
{
  private static String  _id = "IDL:jysk/Controller/palSequence:1.0";

  public static void insert (org.omg.CORBA.Any a, jysk.Pallet[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static jysk.Pallet[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = jysk.PalletHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (jysk.ControllerPackage.palSequenceHelper.id (), "palSequence", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static jysk.Pallet[] read (org.omg.CORBA.portable.InputStream istream)
  {
    jysk.Pallet value[] = null;
    int _len0 = istream.read_long ();
    value = new jysk.Pallet[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = jysk.PalletHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, jysk.Pallet[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      jysk.PalletHelper.write (ostream, value[_i0]);
  }

}
