/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_NativeMethods */

#ifndef _Included_jni_NativeMethods
#define _Included_jni_NativeMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_NativeMethods
 * Method:    displayHelloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_NativeMethods_displayHelloWorld
  (JNIEnv *, jclass);

/*
 * Class:     jni_NativeMethods
 * Method:    dSum
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_jni_NativeMethods_dSum
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     jni_NativeMethods
 * Method:    division
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_jni_NativeMethods_division
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     jni_NativeMethods
 * Method:    area
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_jni_NativeMethods_area
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     jni_NativeMethods
 * Method:    getInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jni_NativeMethods_getInt
  (JNIEnv *, jclass);

/*
 * Class:     jni_NativeMethods
 * Method:    getChar
 * Signature: (C)C
 */
JNIEXPORT jchar JNICALL Java_jni_NativeMethods_getChar
  (JNIEnv *, jclass, jchar);

/*
 * Class:     jni_NativeMethods
 * Method:    getString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_NativeMethods_getString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     jni_NativeMethods
 * Method:    getString2
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_NativeMethods_getString2
  (JNIEnv *, jclass);

/*
 * Class:     jni_NativeMethods
 * Method:    sumOfArray
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_jni_NativeMethods_sumOfArray
  (JNIEnv *, jclass, jdoubleArray);

/*
 * Class:     jni_NativeMethods
 * Method:    circle1
 * Signature: (D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_jni_NativeMethods_circle1
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     jni_NativeMethods
 * Method:    testarrayint
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_jni_NativeMethods_testarrayint
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     jni_NativeMethods
 * Method:    getAllWeights
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_jni_NativeMethods_getAllWeights
  (JNIEnv *, jclass, jdoubleArray);

/*
 * Class:     jni_NativeMethods
 * Method:    getAllArticles
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_jni_NativeMethods_getAllArticles
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     jni_NativeMethods
 * Method:    getAvgVolume
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_jni_NativeMethods_getAvgVolume
  (JNIEnv *, jclass, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
