package jysk;


/**
* jysk/Article.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from jysk.idl
* czwartek, 12 grudzieñ 2013 10:31:55 CET
*/

public final class Article implements org.omg.CORBA.portable.IDLEntity
{
  public int articleid = (int)0;
  public String articlename = null;
  public double articleweight = (double)0;

  public Article ()
  {
  } // ctor

  public Article (int _articleid, String _articlename, double _articleweight)
  {
    articleid = _articleid;
    articlename = _articlename;
    articleweight = _articleweight;
  } // ctor

} // class Article
