package jysk;


/**
* jysk/ControllerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from jysk.idl
* czwartek, 12 grudzieñ 2013 10:31:55 CET
*/

public interface ControllerOperations 
{
  boolean addArticle (jysk.Article art);
  boolean addPallet (jysk.Pallet pal);
  jysk.Article getArticle (int articleid);
  jysk.Pallet getPallet (int palletid);
  jysk.Article[] getArtList ();
  jysk.Pallet[] getPalList ();
} // interface ControllerOperations
