package jysk;

/**
* jysk/ControllerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from jysk.idl
* czwartek, 12 grudzieñ 2013 10:31:55 CET
*/

public final class ControllerHolder implements org.omg.CORBA.portable.Streamable
{
  public jysk.Controller value = null;

  public ControllerHolder ()
  {
  }

  public ControllerHolder (jysk.Controller initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = jysk.ControllerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    jysk.ControllerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return jysk.ControllerHelper.type ();
  }

}
