package jysk;


/**
* jysk/ControllerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from jysk.idl
* czwartek, 12 grudzieñ 2013 10:31:55 CET
*/

public abstract class ControllerPOA extends org.omg.PortableServer.Servant
 implements jysk.ControllerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addArticle", new java.lang.Integer (0));
    _methods.put ("addPallet", new java.lang.Integer (1));
    _methods.put ("getArticle", new java.lang.Integer (2));
    _methods.put ("getPallet", new java.lang.Integer (3));
    _methods.put ("getArtList", new java.lang.Integer (4));
    _methods.put ("getPalList", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // jysk/Controller/addArticle
       {
         jysk.Article art = jysk.ArticleHelper.read (in);
         boolean $result = false;
         $result = this.addArticle (art);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // jysk/Controller/addPallet
       {
         jysk.Pallet pal = jysk.PalletHelper.read (in);
         boolean $result = false;
         $result = this.addPallet (pal);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // jysk/Controller/getArticle
       {
         int articleid = in.read_long ();
         jysk.Article $result = null;
         $result = this.getArticle (articleid);
         out = $rh.createReply();
         jysk.ArticleHelper.write (out, $result);
         break;
       }

       case 3:  // jysk/Controller/getPallet
       {
         int palletid = in.read_long ();
         jysk.Pallet $result = null;
         $result = this.getPallet (palletid);
         out = $rh.createReply();
         jysk.PalletHelper.write (out, $result);
         break;
       }

       case 4:  // jysk/Controller/getArtList
       {
         jysk.Article $result[] = null;
         $result = this.getArtList ();
         out = $rh.createReply();
         jysk.ControllerPackage.artSequenceHelper.write (out, $result);
         break;
       }

       case 5:  // jysk/Controller/getPalList
       {
         jysk.Pallet $result[] = null;
         $result = this.getPalList ();
         out = $rh.createReply();
         jysk.ControllerPackage.palSequenceHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:jysk/Controller:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Controller _this() 
  {
    return ControllerHelper.narrow(
    super._this_object());
  }

  public Controller _this(org.omg.CORBA.ORB orb) 
  {
    return ControllerHelper.narrow(
    super._this_object(orb));
  }


} // class ControllerPOA
