package jysk;


/**
* jysk/CraneHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from jysk.idl
* czwartek, 12 grudzieñ 2013 10:31:55 CET
*/

abstract public class CraneHelper
{
  private static String  _id = "IDL:jysk/Crane:1.0";

  public static void insert (org.omg.CORBA.Any a, jysk.Crane that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static jysk.Crane extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (jysk.CraneHelper.id (), "Crane");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static jysk.Crane read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CraneStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, jysk.Crane value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static jysk.Crane narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof jysk.Crane)
      return (jysk.Crane)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      jysk._CraneStub stub = new jysk._CraneStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static jysk.Crane unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof jysk.Crane)
      return (jysk.Crane)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      jysk._CraneStub stub = new jysk._CraneStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
