package jysk;

/**
* jysk/CraneHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from jysk.idl
* czwartek, 12 grudzieñ 2013 10:31:55 CET
*/

public final class CraneHolder implements org.omg.CORBA.portable.Streamable
{
  public jysk.Crane value = null;

  public CraneHolder ()
  {
  }

  public CraneHolder (jysk.Crane initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = jysk.CraneHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    jysk.CraneHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return jysk.CraneHelper.type ();
  }

}
