package jysk;


/**
* jysk/Crane.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from jysk.idl
* czwartek, 12 grudzieñ 2013 10:31:55 CET
*/

public interface Crane extends CraneOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Crane
