package jysk;


/**
* jysk/GoodsInputOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from jysk.idl
* czwartek, 12 grudzieñ 2013 10:31:55 CET
*/

public interface GoodsInputOperations 
{
  void putOnBelt (jysk.Pallet pal);
} // interface GoodsInputOperations
