package jysk;


/**
* jysk/GoodsInputPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from jysk.idl
* czwartek, 12 grudzieñ 2013 10:31:55 CET
*/

public abstract class GoodsInputPOA extends org.omg.PortableServer.Servant
 implements jysk.GoodsInputOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("putOnBelt", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // jysk/GoodsInput/putOnBelt
       {
         jysk.Pallet pal = jysk.PalletHelper.read (in);
         this.putOnBelt (pal);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:jysk/GoodsInput:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GoodsInput _this() 
  {
    return GoodsInputHelper.narrow(
    super._this_object());
  }

  public GoodsInput _this(org.omg.CORBA.ORB orb) 
  {
    return GoodsInputHelper.narrow(
    super._this_object(orb));
  }


} // class GoodsInputPOA
