package jysk;


/**
* jysk/Pallet.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from jysk.idl
* czwartek, 12 grudzieñ 2013 10:31:55 CET
*/

public final class Pallet implements org.omg.CORBA.portable.IDLEntity
{
  public int palletid = (int)0;
  public int articleid = (int)0;
  public double articleamount = (double)0;
  public double palletweight = (double)0;

  public Pallet ()
  {
  } // ctor

  public Pallet (int _palletid, int _articleid, double _articleamount, double _palletweight)
  {
    palletid = _palletid;
    articleid = _articleid;
    articleamount = _articleamount;
    palletweight = _palletweight;
  } // ctor

} // class Pallet
